version: "2"
run:
  go: "1.25"
  tests: true
linters:
  default: all
  disable:
   - wrapcheck
   - varnamelen
   - testpackage
   - gochecknoglobals
   - forbidigo
   - exhaustruct
   - depguard
   - wsl
  settings:
    errorlint:
      errorf: false
  exclusions:
    rules:
      - linters:
          - funlen
        path: _test\.go